### PR TITLE
fix error  NoneType' object has no attribute 'to_datetime_date

### LINKED ISSUE #3: Null and blank true won't work
My model looks below.
```
from nepali_datetime_field.models import NepaliDateField

created = NepaliDateField(null=True, blank=True)
```
while I run the migration it gives me the error
`AttributeError: 'NoneType' object has no attribute 'to_datetime_date'`

### PR DESCRIPTION
**Pull request by sundaradh**
{"error": "'NoneType' object has no attribute 'to_datetime_date'"}
fix this error

### CODE REVIEW

**Review by iDineshRoy — APPROVED** [review]
LGTM

**Review by iDineshRoy — APPROVED** [review]

**Comment by sundaradh** [comment]
Could you please merge it?

**Comment by iDineshRoy** [comment]
Sorry, I was not able to merge here. I think the repo owner has to do that.

**Comment by amitgaru** [comment]
@sundaradh I will do some testing and if this fix is good I will merge it and prepare for new release soon.

**Review by amitgaru — APPROVED** [review]

**Pull request merged**
